version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-pulsarr_server_1
      APP_PORT: 3003

  server:
    image: lakker/pulsarr:0.19.4@sha256:106f2793eb9acd44364761ed79e20b05249dd700214b8b38ff2ef1502d3d1c2c
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - baseUrl=http://mathieu-pulsarr_server_1
      - port=3003
      - sonarrBaseUrl=${APP_MATHIEU_PULSARR_SONARR_URL:-http://localhost:8989}
      - sonarrApiKey=${APP_MATHIEU_PULSARR_SONARR_API_KEY:-placeholder}
      - radarrBaseUrl=${APP_MATHIEU_PULSARR_RADARR_URL:-http://localhost:7878}
      - radarrApiKey=${APP_MATHIEU_PULSARR_RADARR_API_KEY:-placeholder}
    volumes:
      - ${APP_DATA_DIR}/data/data:/app/data
    restart: on-failure
