version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-suggestarr_server_1
      APP_PORT: 5000

  server:
    image: ciuse99/suggestarr:v2.10.0@sha256:aaffd551459fcaf9f784cb4a76169f333ef406ac8e4e1f4bf3fd44851a210e8c
    init: true
    environment:
      - TZ=Europe/Paris
      - SUGGESTARR_PORT=5000
      - LOG_LEVEL=info
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config/config_files
    restart: on-failure
