version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-suggestarr_server_1
      APP_PORT: 5000

  server:
    image: ciuse99/suggestarr:v2.16.0@sha256:932b298a2ad5e888342df81434cacd7641df9f0b99478a1243dbc436590f2a7e
    init: true
    environment:
      - TZ=Etc/UTC
      - SUGGESTARR_PORT=5000
      - LOG_LEVEL=info
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config/config_files
    restart: on-failure
