version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-suggestarr_server_1
      APP_PORT: 5000

  server:
    image: ciuse99/suggestarr:v2.16.1@sha256:b22d3311bc1a8b8d147170757569f2228be6932db034cb2fc0c0a723e11b4a7e
    init: true
    environment:
      - TZ=Etc/UTC
      - SUGGESTARR_PORT=5000
      - LOG_LEVEL=info
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config/config_files
    restart: on-failure
