version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-tdarr_server_1
      APP_PORT: 8265

  server:
    image: haveagitgat/tdarr:2.90.01@sha256:da53b682b85ad74241557ed6ed840504391dededac9824b5e27b6d1bba24335a
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - internalNode=true
      - nodeName=InternalNode
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APP_DATA_DIR}/data/server:/app/server
      - ${APP_DATA_DIR}/data/configs:/app/configs
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - ${APP_DATA_DIR}/data/transcode:/temp
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
