version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-tdarr_server_1
      APP_PORT: 8265

  server:
    image: haveagitgat/tdarr:2.95.01@sha256:6b4dcd9a20dc80a26d06b50378bdfa6955f2d37e413bf4c52d93a4bb37e74afc
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - internalNode=true
      - nodeName=InternalNode
    volumes:
      - ${APP_DATA_DIR}/data/server:/app/server
      - ${APP_DATA_DIR}/data/configs:/app/configs
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - ${APP_DATA_DIR}/data/transcode:/temp
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
