version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-tdarr_server_1
      APP_PORT: 8265

  server:
    image: haveagitgat/tdarr:2.86.01@sha256:45742f00e51a58553844c8b13d97e7ae9b2ee9a056bd8e5993d9a8282a45a23f
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - internalNode=true
      - nodeName=InternalNode
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APP_DATA_DIR}/data/server:/app/server
      - ${APP_DATA_DIR}/data/configs:/app/configs
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - ${APP_DATA_DIR}/data/transcode:/temp
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
