version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-maintainerr_server_1
      APP_PORT: 6246

  server:
    image: ghcr.io/maintainerr/maintainerr:3.29.0@sha256:7487d374290e59add65407ec295629e489f9057dbf18e2a9dff70d6201ffb6f9
    init: true
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/opt-data:/opt/data
    restart: on-failure
