version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-maintainerr_server_1
      APP_PORT: 6246

  server:
    image: ghcr.io/maintainerr/maintainerr:3.17.1@sha256:95e429451ea45380430d260450ab301eed9ce91fbcba5f94cf8507bd0bac0d08
    init: true
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/opt-data:/opt/data
    restart: on-failure
