version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-maintainerr_server_1
      APP_PORT: 6246

  server:
    image: ghcr.io/maintainerr/maintainerr:3.20.1@sha256:ce7ff52afa146dfc05c2c2304df8141e0086f14a803bdbef0d870e5b914f0dee
    init: true
    environment:
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/opt-data:/opt/data
    restart: on-failure
