version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-slskd_server_1
      APP_PORT: 5030

  server:
    image: slskd/slskd:0.26.0@sha256:ecd4026d4f8fb504e2cc55323efa2c1f5b56d20d3686b018249cc36b48ea17a6
    init: true
    user: "1000:1000"
    environment:
      - TZ=Europe/Paris
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_DOWNLOADS_DIR=/downloads/soulseek/complete
      - SLSKD_INCOMPLETE_DIR=/downloads/soulseek/incomplete
    ports:
      - "50300:50300/tcp"
    volumes:
      - ${APP_DATA_DIR}/data/app:/app
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
