version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-lingarr_server_1
      APP_PORT: 9876

  server:
    image: ghcr.io/lingarr-translate/lingarr:1.4.0@sha256:8f392cf1efe718e0fcbc735d6d82df0b0bf86594bf64998aad85e8f306263774
    user: "1000:1000"
    init: true
    environment:
      - TZ=Etc/UTC
      - ASPNETCORE_URLS=http://+:9876
      - DB_CONNECTION=sqlite
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
