version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-kapowarr_server_1
      APP_PORT: 5656

  server:
    image: mrcas/kapowarr:v1.3.2@sha256:cd3f004caff59636dde73b06df5b2f8068b485b47ff5fe82f6129562c0f2ac3b
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db
      - ${APP_DATA_DIR}/data/temp_downloads:/app/temp_downloads
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
