version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-chaptarr_server_1
      APP_PORT: 8789

  server:
    image: robertlordhood/chaptarr:0.9.911@sha256:ccbe157f88f33d085d12a3e5d7cfb9d5b15f89d69b6eba984f789064d21e1b85
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
