version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-chaptarr_server_1
      APP_PORT: 8789

  server:
    image: robertlordhood/chaptarr:0.9.914@sha256:4780b36440dc055a404f86da089f124d41e3330d32eeb92837f65fb5c82a348c
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
