version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-chaptarr_server_1
      APP_PORT: 8789

  server:
    image: robertlordhood/chaptarr:0.9.906@sha256:6bed0be1e9f100b4c17288291ac3487d99268d899302eb5e00804fa6afde9ee8
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
