version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-boxarr_server_1
      APP_PORT: 8888

  server:
    image: ghcr.io/iongpt/boxarr:2.0.0@sha256:c1aba508d8e5d69db4745861ff33f09c679c1e7386f589c3d6781970d71d7b3a
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
