version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-boxarr_server_1
      APP_PORT: 8888

  server:
    image: ghcr.io/iongpt/boxarr:2.1.0@sha256:f4e99515090a2dde550a61beaa0caa6f7e2c31ce2b80ffe8a5f6424059317fad
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
