version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-muxarr_server_1
      APP_PORT: 8183

  server:
    image: ghcr.io/kirovair/muxarr:0.9.9@sha256:b506ac7107ab166fe1d65959e04f15a07692f230a3da823329f51628cb25b709
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
