version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-tunarr_server_1
      APP_PORT: 8000
      PROXY_AUTH_WHITELIST: "/device.xml,/discover.json,/lineup.json,/lineup_status.json,/stream/*,/streams/*,/api/channels.m3u,/api/xmltv.xml"

  server:
    image: ghcr.io/chrisbenincasa/tunarr:2026.10.1@sha256:139f331c8289bf52b748b4af1da6497dd92a88627e89a430b46a46034592359f
    environment:
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config/tunarr
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads:ro
    restart: on-failure
