version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-tracearr_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/connorgallopo/tracearr:supervised-2.7.0@sha256:b7c008cc2145b57ac17d8d7364b0eb64ea2671c1416862ea2730ebcccfc16499
    init: true
    shm_size: 512mb
    environment:
      - TZ=Etc/UTC
      - LOG_LEVEL=info
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/data/postgres
      - ${APP_DATA_DIR}/data/redis:/data/redis
      - ${APP_DATA_DIR}/data/tracearr:/data/tracearr
      - ${APP_DATA_DIR}/data/tracearr/backup:/data/backup
    restart: on-failure
