version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-vitals_server_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/v1/*,/health"

  server:
    image: ghcr.io/mathieuletyrant/vitals:0.2.1@sha256:7facc3c4ba0e63321fad981766531c8f48936530da30372028c143f59dbcd85d
    environment:
      VITALS_TOKEN: ${APP_PASSWORD:?APP_PASSWORD is not set}
    restart: on-failure
