version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-vitals_server_1
      APP_PORT: 3000
      PROXY_AUTH_WHITELIST: "/v1/*,/health"

  server:
    image: ghcr.io/mathieuletyrant/vitals:0.2.2@sha256:550cae73b79a0a5e8cd25c2605239ae19317ad6bc05ec6b2791bf4ee736f5d0b
    environment:
      VITALS_TOKEN: ${APP_PASSWORD:?APP_PASSWORD is not set}
    restart: on-failure
