version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-sportarr_server_1
      APP_PORT: 1867

  server:
    image: sportarr/sportarr:4.0.1022.1102@sha256:6120a00c7d6587626388a40548694a83628eca62ab9fbf8b13681934f4faf4ca
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
