version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-sportarr_server_1
      APP_PORT: 1867

  server:
    image: sportarr/sportarr:4.1.1.1111@sha256:ee39b1a1f7b8485af8f74acd82929287b7e118d41d48e9e2084e9e618752c522
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads:/downloads
    restart: on-failure
