version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-scryer_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/scryer-media/scryer:0.21.14@sha256:6a90d501e6b76f457836b2742dc81cf99bf5cc8b640b2a7bd42bde0e48d16319
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
