version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-scryer_server_1
      APP_PORT: 8080

  server:
    image: ghcr.io/scryer-media/scryer:0.21.9@sha256:48ee8f251312cd04c33ff8b727bd759776075dcf82e2e074c8ebf8dedc22ce0c
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
