version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-arr-mcp_server_1
      APP_PORT: 6060
      PROXY_AUTH_WHITELIST: "/mcp*,/.well-known/*,/healthz"

  server:
    image: ghcr.io/bardesss/arr-mcp:1.44.0@sha256:f9ac224023d7530456304ae81199c94a109ce5bef8de76860d7c3535b456f96c
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
