version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mathieu-sublarr_server_1
      APP_PORT: 5765

  server:
    image: ghcr.io/abrechen2/sublarr:1.16.0@sha256:52b388ea2dfe71ae696396011842208f2e225a403d1ba94379087c4cbbfa1e28
    init: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBLARR_CORS_ORIGINS=*
      - SUBLARR_MEDIA_PATH=/downloads
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
