name: Validate apps

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - run: pip install pyyaml

      - name: Validate app definitions
        run: python3 .github/scripts/validate_apps.py
